In [79]:
import glob
import pandas as pd
import warnings
import numpy as np

In [166]:
audio_paths=glob.glob('../data/audio/*/*.wav')

In [167]:
df=pd.DataFrame()
warnings.filterwarnings('ignore')

for path in audio_paths:
    path_split=path.split('/')
    part=path_split[-2]
    filename=path_split[-1]
    basename=filename.split('.')[0]
    dict_={'filename':filename,'partition':part,'basename':basename}
    df=df.append(dict_,True)

In [168]:
for i,basename in enumerate(df.basename):
    df_sample=df[df['basename']==basename]
    n=df_sample.shape[0]
    n_train=df_sample[df_sample['partition']=='Train'].shape[0]
    n_test=df_sample[df_sample['partition']=='Test'].shape[0]
    n_val=df_sample[df_sample['partition']=='Val'].shape[0]
    df.loc[i,'n_segments']=n
    df.loc[i,'n_train']=n_train
    df.loc[i,'n_val']=n_val
    df.loc[i,'n_test']=n_test

In [169]:
df.to_csv('../data/dataset_description.csv')

In [170]:
df_reduced=df.drop_duplicates(subset='basename',ignore_index=True).drop(columns=['filename','partition'])

In [228]:
df_reduced

         basename  n_segments  n_train  n_val  n_test
0     mDRMCwSD3Ms         2.0      0.0    2.0     0.0
1     nUazOUcW_AM         3.0      2.0    1.0     0.0
2     8AnIttmflwI         4.0      1.0    3.0     0.0
3     XB81sertsYU         2.0      1.0    1.0     0.0
4     alucqviYJFE         6.0      4.0    2.0     0.0
...           ...         ...      ...    ...     ...
3055  -ZP25UpJeJ4         1.0      0.0    0.0     1.0
3056  pslp6X3OWy0         1.0      0.0    0.0     1.0
3057  UWG7Jyqc1CY         1.0      0.0    0.0     1.0
3058  Cv_QK9bPagQ         1.0      0.0    0.0     1.0
3059  cpch8WDydcM         1.0      0.0    0.0     1.0

[3060 rows x 5 columns]

In [229]:
list_=[]
segments=0
list_names=[]

for i,j in zip([1836,612],[6000,2000]):
    print(i,j)
    while segments!=j:
        a=df_reduced.sample(i,replace=False)
        segments=np.sum(a.n_segments.values)
    list_names=list(a.basename.values)
    list_.append(list_names)
    df_reduced=df_reduced[~df_reduced['basename'].isin(list_)]
#list_names=list(df_reduced.basename.values)
#list_.append(list_names)

1836 6000
612 2000

In [230]:
len(list_[0])

1836

In [231]:
len(list_[1])

612

In [232]:
len(list_[2])

3060

In [202]:
df_new=df.drop(columns='partition')

In [217]:
parts=['Train','Val','Test']

In [219]:
df_new.drop_duplicates(subset='filename')

,filename,basename,n_segments,n_train,n_val,n_test,part_new
0,mDRMCwSD3Ms.001.wav,mDRMCwSD3Ms,2.0,0.0,2.0,0.0,Train
1,nUazOUcW_AM.002.wav,nUazOUcW_AM,3.0,2.0,1.0,0.0,Train
2,8AnIttmflwI.000.wav,8AnIttmflwI,4.0,1.0,3.0,0.0,Test
3,XB81sertsYU.004.wav,XB81sertsYU,2.0,1.0,1.0,0.0,Train
4,alucqviYJFE.005.wav,alucqviYJFE,6.0,4.0,2.0,0.0,Train
...,...,...,...,...,...,...,...
9995,SkNO4x-LSgE.001.wav,SkNO4x-LSgE,5.0,2.0,1.0,2.0,Train
9996,QdafN9Y_j-Y.003.wav,QdafN9Y_j-Y,4.0,1.0,2.0,1.0,Train
9997,JJs_HTelie4.000.wav,JJs_HTelie4,2.0,1.0,0.0,1.0,Train
9998,cWvZnl5XjwI.002.wav,cWvZnl5XjwI,3.0,0.0,0.0,3.0,Train
9999,1uC-2TZqplE.003.wav,1uC-2TZqplE,4.0,0.0,3.0,1.0,Test

In [220]:
df_final=pd.DataFrame()

for k,part in enumerate(parts):
    df_new.loc[df_new['basename'].isin(list_[k]),'part_new']=part

In [221]:
df_new

,filename,basename,n_segments,n_train,n_val,n_test,part_new
0,mDRMCwSD3Ms.001.wav,mDRMCwSD3Ms,2.0,0.0,2.0,0.0,Train
1,nUazOUcW_AM.002.wav,nUazOUcW_AM,3.0,2.0,1.0,0.0,Train
2,8AnIttmflwI.000.wav,8AnIttmflwI,4.0,1.0,3.0,0.0,Test
3,XB81sertsYU.004.wav,XB81sertsYU,2.0,1.0,1.0,0.0,Train
4,alucqviYJFE.005.wav,alucqviYJFE,6.0,4.0,2.0,0.0,Train
...,...,...,...,...,...,...,...
9995,SkNO4x-LSgE.001.wav,SkNO4x-LSgE,5.0,2.0,1.0,2.0,Train
9996,QdafN9Y_j-Y.003.wav,QdafN9Y_j-Y,4.0,1.0,2.0,1.0,Train
9997,JJs_HTelie4.000.wav,JJs_HTelie4,2.0,1.0,0.0,1.0,Train
9998,cWvZnl5XjwI.002.wav,cWvZnl5XjwI,3.0,0.0,0.0,3.0,Train
9999,1uC-2TZqplE.003.wav,1uC-2TZqplE,4.0,0.0,3.0,1.0,Train

In [223]:
df_new[df_new['part_new'].isna()]

,filename,basename,n_segments,n_train,n_val,n_test,part_new
11,AR3UwbmgKuQ.002.wav,AR3UwbmgKuQ,6.0,4.0,2.0,0.0,NaN
16,PXJfSp2WvVY.004.wav,PXJfSp2WvVY,2.0,0.0,2.0,0.0,NaN
21,X1EjfXX3NTk.002.wav,X1EjfXX3NTk,6.0,3.0,2.0,1.0,NaN
40,ApCq0dwH1Ak.000.wav,ApCq0dwH1Ak,1.0,0.0,1.0,0.0,NaN
44,oJPdfhG4hT0.000.wav,oJPdfhG4hT0,3.0,2.0,1.0,0.0,NaN
...,...,...,...,...,...,...,...
9922,bkzgccBFztM.005.wav,bkzgccBFztM,5.0,3.0,1.0,1.0,NaN
9923,RWhyKkFI3zw.000.wav,RWhyKkFI3zw,6.0,3.0,1.0,2.0,NaN
9937,ogSLrHVeqLI.002.wav,ogSLrHVeqLI,2.0,1.0,0.0,1.0,NaN
9951,xYXVkQOmSfk.004.wav,xYXVkQOmSfk,3.0,0.0,2.0,1.0,NaN
9978,nLuAoNAOGcQ.001.wav,nLuAoNAOGcQ,3.0,1.0,0.0,2.0,NaN